### ISSUE TITLE
操作反馈中的 ‘’动作面板‘’和 ‘’分享面板 ‘’ 弹框出现后   切换左侧侧边栏 弹框不消失

### ISSUE THREAD

**Issue by 787539498** [hellof2e/quark-design#10]
分享面板页面：
![图片](https://user-images.githubusercontent.com/57472841/198951324-48dc6363-7442-429f-aa2e-020ef7ffc4b6.png)
![图片](https://user-images.githubusercontent.com/57472841/198951338-b9c19e9b-5df9-4aa0-83bc-5a4eb6690732.png)
动作面板页面：
![图片](https://user-images.githubusercontent.com/57472841/198951388-135e9bdb-9e0c-4d62-b7d5-cc16cbbd5de6.png)
![图片](https://user-images.githubusercontent.com/57472841/198951598-3cd23b8d-96c2-42de-b22c-68f8d1e95e32.png)

**Comment by 787539498** [comment]
MarketDialog 营销弹窗页面也有此情况：
![图片](https://user-images.githubusercontent.com/57472841/198954961-c3ea32f2-75d8-4cb4-bab6-4401f22280d2.png)

**Comment by xxxsf** [comment]
收到

**Comment by sanqi-med** [comment]
已修复
