### ISSUE TITLE
为什么不直接用lit，而是自己造了一个轮子呢？方便分享一下背后的考量吗？

### ISSUE THREAD

**Issue by chensce** [hellof2e/quark-design#104]
### 这个功能解决了什么问题

lit是google开发的web component的辅助框架，大小也不大，使用起来比较灵活。

### 你建议的方案是什么

直接用lit

**Comment by sanqi-med** [comment]
1.  依赖 Lit 的话，后期 Quark Design 的技术规划将受限于第三方，这是主要考量的因素。
2.  Lit 的能力我们基本上都包含了，但 Lit 不能使用 jsx 编写组件，这个是不符合开发者习惯的。
