### ISSUE TITLE
关于 README 中组件库体积的疑问

### ISSUE THREAD

**Issue by chenjiahan** [hellof2e/quark-design#109]
目前 README 中对几个组件库的 CDN 文件体积进行了对比：

![image](https://user-images.githubusercontent.com/7237365/200544048-9baa0f04-ca78-4d12-ba62-7f468d5625a3.png)

以上体积数据与我验证的结果并不相符，请问是否是数据统计有误？

![image](https://user-images.githubusercontent.com/7237365/200545117-a88f64b6-78bf-410f-a271-9ead4e890496.png)

- https://fastly.jsdelivr.net/npm/vant@3.6.5/lib/vant.min.js
- https://fastly.jsdelivr.net/npm/quarkd@1.0.11/umd/index.js
- https://cdn.jsdelivr.net/npm/@nutui/nutui@2.3.11/dist/nutui.min.js

### 你建议的方案是什么

明确数据统计方式，或修正数据。

**Comment by xxxsf** [comment]
vant和nutui中需要运行时vue+样式引入，这些你都没有统计，我们所有的都统计进去了。

**Comment by chenjiahan** [comment]
了解，CSS 确实应该算进去。

但既然体积数据是拿 「Quark + 无框架」对比「其他组件库 + 框架体积」，最好在表格下方加个说明，以免误导用户。

**Comment by xxxsf** [comment]
好的，感谢您的反馈，我回头加下🌹
