### ISSUE TITLE
npx lerna run --scope quarkd test    error

### ISSUE THREAD

**Issue by liaohainan** [hellof2e/quark-design#113]
### Quark Design 版本

all

### 重现步骤

执行npx lerna run --scope quarkd test 测试命令报错

lerna notice cli v5.1.8
lerna info versioning independent
lerna notice filter including "quarkd"
lerna info filter [ 'quarkd' ]
lerna info Executing command in 1 package: "yarn run test"
lerna ERR! yarn run test exited 1 in 'quarkd'
lerna ERR! yarn run test stdout:
yarn run v1.22.18
$ karma start  --timeout 10000

START:
08 11 2022 22:50:51.021:WARN [filelist]: Pattern "/Users/tang/Documents/mian/quark-design/packages/quark/__snapshots__/**/*.md" does not match any file.
08 11 2022 22:50:51.022:WARN [filelist]: Pattern "/Users/tang/Documents/mian/quark-design/packages/quark/src/packages/**/*.test.js" does not match any file.
08 11 2022 22:50:51.037:INFO [karma-server]: Karma v5.2.3 server started at http://localhost:9876/
08 11 2022 22:50:51.037:INFO [launcher]: Launching browsers ChromeHeadlessNoSandbox with concurrency unlimited
08 11 2022 22:50:51.040:INFO [launcher]: Starting browser ChromeHeadless
08 11 2022 22:50:51.569:INFO [Chrome Headless 107.0.5304.87 (Mac OS 10.15.7)]: Connected on socket M9TcB-qiw6W1uWxMAAAA with id 79500159

Finished in 0 secs / 0 secs @ 22:50:51 GMT+0800 (中国标准时间)

SUMMARY:
✔ 0 tests completed
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run test stderr:
warning package.json: No license field
(node:68367) [log4js-node-DEP0004] DeprecationWarning: Pattern %d{DATE} is deprecated due to the confusion it causes when used. Please use %d{DATETIME} instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:68367) [log4js-node-DEP0004] DeprecationWarning: Pattern %d{DATE} is deprecated due to the confusion it causes when used. Please use %d{DATETIME} instead.
(node:68367) [log4js-node-DEP0004] DeprecationWarning: Pattern %d{DATE} is deprecated due to the confusion it causes when used. Please use %d{DATETIME} instead.
(node:68367) [log4js-node-DEP0004] DeprecationWarning: Pattern %d{DATE} is deprecated due to the confusion it causes when used. Please use %d{DATETIME} instead.
(node:68367) [log4js-node-DEP0004] DeprecationWarning: Pattern %d{DATE} is deprecated due to the confusion it causes when used. Please use %d{DATETIME} instead.
(node:68367) [log4js-node-DEP0004] DeprecationWarning: Pattern %d{DATE} is deprecated due to the confusion it causes when used. Please use %d{DATETIME} instead.
error Command failed with exit code 1.
lerna ERR! yarn run test exited 1 in 'quarkd'

**Comment by yuhaiyang1** [comment]
[https://github.com/hellof2e/quark-design/commit/29dc31b8d5bff16819f092b553e1460127173626](url)
已修复

**Comment by yuhaiyang1** [comment]
希望能继续优化，在跑马灯上面点击暂停/开始,
