### ISSUE TITLE
[官方文档] Chrome浏览器页面滚动十分卡顿，且滚动会导致地址栏闪烁，地址栏内容消失

### ISSUE THREAD

**Issue by CurrrryChen** [hellof2e/quark-design#130]
### 这个功能解决了什么问题

chrome version:107.0.5304.87（正式版本） (x86_64)
OS version: Macos Catalina 10.15.7

<img width="1184" alt="Snipaste_2022-11-12_22-12-51" src="https://user-images.githubusercontent.com/23257507/201478353-9c228f83-f2a1-4c03-aeaf-c61be6d6aaf2.png">

### 你建议的方案是什么

页面滚动不会卡顿，且浏览器地址栏不会闪烁

**Comment by xxxsf** [comment]
问题无法重现，请提供更多报错信息 @CurrrryChen

**Comment by CurrrryChen** [comment]
> 问题无法重现，请提供更多报错信息 @CurrrryChen

没有报错信息，就是卡，Safari访问正常

**Comment by xxxsf** [comment]
方便的话，再提供详细一点的bug描述吧，不然无法定位问题。先关了
