### ISSUE TITLE
【文档】双击按钮会莫名选中按钮下面的文字

### ISSUE THREAD

**Issue by xxxsf** [hellof2e/quark-design#134]
### Other instructions(其他说明)

双击按钮会莫名选中按钮下面的文字
![image](https://user-images.githubusercontent.com/14307551/201571967-103f008f-a0b4-46c8-9a61-e3bb76c4a98d.png)

**Comment by thinkasany** [comment]
@property()
  onselectstart: any = "return false", 似乎加上这个可以解决

**Comment by sanqi-med** [comment]
已修复
