### ISSUE TITLE
.gitignore 文件里要忽视 types 文件吗？

### ISSUE THREAD

**Issue by NoTwoBoy** [hellof2e/quark-design#155]
### A description of the problem, steps to reproduce, or with code samples, can be hosted on a GitHub repository with a link to the repository. (问题说明，重现步骤，或附上代码示例，可存放 GitHub 仓库并提供仓库链接。)

<img width="557" alt="image" src="https://user-images.githubusercontent.com/74694190/202354073-fa5e86d4-5c3f-40c5-9d46-6f43b7f9ba5a.png">

**Comment by sanqi-med** [comment]
要的，types 文件是打包时生成的
