### ISSUE TITLE
sticky 的offsettop属性为什么单位只能是vw

### ISSUE THREAD

**Issue by liaohainan** [hellof2e/quark-design#165]
### A description of the problem, steps to reproduce, or with code samples, can be hosted on a GitHub repository with a link to the repository. (问题说明，重现步骤，或附上代码示例，可存放 GitHub 仓库并提供仓库链接。)

一时没能理解sticky 的offsettop属性为什么单位只能是vw，应该能写各种单位尺寸才对吧，内部还使用了convertVw方法，写了其他单位，就变成NaN了，
如果只能限制一个单位，也应该是vh吧

**Comment by sanqi-med** [comment]
欢迎提PR哦，其它单位理论上也应该要支持

**Comment by sanqi-med** [comment]
已支持： https://github.com/hellof2e/quark-design/pull/167
