### ISSUE TITLE
vite 引入报错

### ISSUE THREAD

**Issue by h7ml** [hellof2e/quark-design#166]
### A description of the problem, steps to reproduce, or with code samples, can be hosted on a GitHub repository with a link to the repository. (问题说明，重现步骤，或附上代码示例，可存放 GitHub 仓库并提供仓库链接。)

![image](https://user-images.githubusercontent.com/55233292/203250131-a45b1591-f695-4589-88c4-489a16203d46.png)

**Comment by sanqi-med** [comment]
1.0.23版本已修复，https://github.com/hellof2e/quark-design/commit/adbc68c3a399e213449a3b7a8e24faf1858f0189
