### ISSUE TITLE
文档站点的更新日志没同步

### ISSUE THREAD

**Issue by thinkasany** [hellof2e/quark-design#171]
### A description of the problem, steps to reproduce, or with code samples, can be hosted on a GitHub repository with a link to the repository. (问题说明，重现步骤，或附上代码示例，可存放 GitHub 仓库并提供仓库链接。)

问题说明：文档站点的更新日志没同步
期望： 同步更新 changelog

**Comment by xxxsf** [comment]
好的，我明天处理
