### ISSUE TITLE
[uploader]禁止上传的的图标是不是应该有点变化

### ISSUE THREAD

**Issue by liaohainan** [hellof2e/quark-design#191]
### A description of the problem, steps to reproduce, or with code samples, can be hosted on a GitHub repository with a link to the repository. (问题说明，重现步骤，或附上代码示例，可存放 GitHub 仓库并提供仓库链接。)

禁止上传的的图标是不是应该有点变化，和非禁止样子一样，点击也没提示

**Comment by yuhaiyang1** [comment]
已减少透明度
