### ISSUE TITLE
toast组件弹出时,切换页面toast不会马上关闭

### ISSUE THREAD

**Issue by Moonofweisheng** [hellof2e/quark-design#197]
### 
可以在官方demo中复现，不知道有没有什么好的解决办法。

**Comment by yoyo837** [comment]
至于demo是不是我说的这个场景, 我没有去核对.

**Comment by sanqi-med** [comment]
> 可以在官方demo中复现，不知道有没有什么好的解决办法。

这是正常的设计哈，正如@yoyou837所解释的那样
