### ISSUE TITLE
关于使用 Microsoft Edge 浏览器浏览组件库官网组件介绍页面明显卡顿问题

### ISSUE THREAD

**Issue by zzinx58** [hellof2e/quark-design#201]
### A description of the problem, steps to reproduce, or with code samples, can be hosted on a GitHub repository with a link to the repository. (问题说明，重现步骤，或附上代码示例，可存放 GitHub 仓库并提供仓库链接。)

具体页面 Url：https://quark-design.hellobike.com/#/zh-CN/component/button

具体体现：
1.左侧内容目录部分可以流畅滚动，右侧组件使用指南部分滚动卡顿。
2.在 Safari 浏览器没有此现象。

附上视频：

https://user-images.githubusercontent.com/77034104/206630067-69aa2406-4b38-4da5-ba07-febfd7184ddb.mp4

**Comment by StevenLikeWatermelon** [comment]
确实很卡

**Comment by xxxsf** [comment]
@StevenLikeWatermelon  你的也是edge 浏览器吗？

**Comment by xxxsf** [comment]
后面考虑重构，先关掉了
