### ISSUE TITLE
Why css unit is converted in the lib?

### ISSUE THREAD

**Issue by HuaiKong** [hellof2e/quark-design#210]
### A description of the problem, steps to reproduce, or with code samples, can be hosted on a GitHub repository with a link to the repository. (问题说明，重现步骤，或附上代码示例，可存放 GitHub 仓库并提供仓库链接。)

在库里就做了 vw 转化, 不想跟着转的话对齐都很麻烦了, 这个不用做成默认行为吧?

**Comment by sanqi-med** [comment]
移动端的组件绝大部分场景都是需要适配的，Web Components 组件有它的特殊性，它的 css 是无法穿透的，也就是业务工程无法通过配置 postcss 来改变 Web components 内部的 css 来做到适配

**Comment by HuaiKong** [comment]
好的, 感谢解答, 其实感觉到是原生的限制了
