### ISSUE TITLE
太差劲了，组件要啥没啥

### ISSUE THREAD

**Issue by wenjie88** [hellof2e/quark-design#211]
### A description of the problem, steps to reproduce, or with code samples, can be hosted on a GitHub repository with a link to the repository. (问题说明，重现步骤，或附上代码示例，可存放 GitHub 仓库并提供仓库链接。)

quark-textarea， 连动态绑定值都不行， 这框架有什么毛用

**Comment by sanqi-med** [comment]
这个是原生组件哦，和Vue不太一样，另外并不是所有框架都需要动态绑定，React就没有动态绑定
