### ISSUE TITLE
有些不懂这个组件库的逻辑

### ISSUE THREAD

**Issue by Elm1992** [hellof2e/quark-design#212]
### A description of the problem, steps to reproduce, or with code samples, can be hosted on a GitHub repository with a link to the repository. (问题说明，重现步骤，或附上代码示例，可存放 GitHub 仓库并提供仓库链接。)

随便找个组件看了一下，就拿 Stepper 组件来说 <quark-stepper min="5" max="12" /> 限制了范围之后的值就删不掉了，到实际业务场景假如设置一个非必填题，那如果用户不下心填错了，怎么删都删不掉那要重新刷新页面嘛？

再一个就更怪了，为什么开始只能输入0.x, 不能输入5.x,6.x...？

在一个就是输入一个2，按一下删除会变成 0？，再按一下才是null？

**Comment by sanqi-med** [comment]
我们看下这个问题

**Comment by yuhaiyang1** [comment]
官网已修复

**Comment by sanqi-med** [comment]
> 官网已修复

https://github.com/hellof2e/quark-design/commit/0e017dfb89d16881933ba99f571a41f8067caf42

**Comment by Elm1992** [comment]
@sanqi-med 变更回调那个demo，输入2.1再按两个减号
![image](https://user-images.githubusercontent.com/26025205/211513676-a38a452e-d161-4938-a567-ae96b12e9359.png)

再一个输入02失焦之后变成值还是02，但这会应该变成2更好了吧，但这个我觉得算不算问题都还能接受，但是不管是02还是22，在中间加个小数点立马就变成了0，这就不合理了，不应该是0.2或是2.2吗
