### ISSUE TITLE
亲, 更新日志建议坚持一下

### ISSUE THREAD

**Issue by yoyo837** [hellof2e/quark-design#217]
### A description of the problem, steps to reproduce, or with code samples, can be hosted on a GitHub repository with a link to the repository. (问题说明，重现步骤，或附上代码示例，可存放 GitHub 仓库并提供仓库链接。)

<img width="239" alt="image" src="https://user-images.githubusercontent.com/6134547/217129243-e79bc12c-9627-4352-864c-a678eea82578.png">

**Comment by yuhaiyang1** [comment]
最近我们中心在这边 [https://github.com/hellof2e/quark](url)

**Comment by yoyo837** [comment]
中心?重心? 重心在功能本身, 应该更需要明细的chagnelog吧? 这样感兴趣的人才相对会更多.

**Comment by yoyo837** [comment]
https://github.com/hellof2e/quark 很不错的东西. 👍
