### ISSUE TITLE
onChange is unnecessary

### ISSUE THREAD

**Issue by zhaoyiming0803** [hellof2e/quark-design#220]
### A description of the problem, steps to reproduce, or with code samples, can be hosted on a GitHub repository with a link to the repository. (问题说明，重现步骤，或附上代码示例，可存放 GitHub 仓库并提供仓库链接。)

![onChange](https://user-images.githubusercontent.com/25874685/223657416-c6021314-04c6-485f-afa7-8a8062393e5f.png)

**Comment by sanqi-med** [comment]
这个onChange 是必须的哦，因为这些表单组件是受控组件，不使用onChange接收变更，组件就没使用意义了哦

**Comment by zhaoyiming0803** [comment]
> 这个onChange 是必须的哦，因为这些表单组件是受控组件，不使用onChange接收变更，组件就没使用意义了哦

有么有准备开源一套 PC 用的 Web Component 组件，或有合适的可以推荐下吗？

**Comment by sanqi-med** [comment]
> 

暂时还没有计划哦，有需要的话可以基于我们的quarkc ，开发一套自己的 PC 端  web components组件

**Comment by sanqi-med** [comment]
> > 这个onChange 是必须的哦，因为这些表单组件是受控组件，不使用onChange接收变更，组件就没使用意义了哦
> 
> 有么有准备开源一套 PC 用的 Web Component 组件，或有合适的可以推荐下吗？

暂时还没有计划哦，有需要的话可以基于我们的quarkc ，开发一套自己的 PC 端  web components组件

**Comment by zhaoyiming0803** [comment]
> quarkc

quarkc 只有 npm 包，此仓库代码中没有吧？

**Comment by zhaoyiming0803** [comment]
> > > 这个onChange 是必须的哦，因为这些表单组件是受控组件，不使用onChange接收变更，组件就没使用意义了哦
> > 
> > 
> > 有么有准备开源一套 PC 用的 Web Component 组件，或有合适的可以推荐下吗？
> 
> 暂时还没有计划哦，有需要的话可以基于我们的quarkc ，开发一套自己的 PC 端 web components组件

quarkc 只有 npm 包，此仓库代码中没有吧？

**Comment by sanqi-med** [comment]
> quarkc 只有 npm 包，此仓库代码中没有吧？

https://quark.hellobike.com/ 可以参考下文档哦，quarkc 已独立成新的仓库
