### ISSUE TITLE
官方文档样式错误

### ISSUE THREAD

**Issue by yyues** [hellof2e/quark-design#232]
### A description of the problem, steps to reproduce, or with code samples, can be hosted on a GitHub repository with a link to the repository. (问题说明，重现步骤，或附上代码示例，可存放 GitHub 仓库并提供仓库链接。)

![image](https://user-images.githubusercontent.com/66165070/227155691-9a3b0022-277f-44eb-9071-7251e2e2a9cf.png)
![image](https://user-images.githubusercontent.com/66165070/227155880-5acdd04f-9090-4e1b-8454-8b867a57b80c.png)
等等，新UI组件设计很好，尚未具体使用，但文档不应该有这种错误啊

**Comment by jiesir** [comment]
一生二，二生三，三生万物，看来vant就是这个三！！！哈哈

**Comment by yx376642000** [comment]
已收到问题，我们尽快安排处理

**Comment by yx376642000** [comment]
已修复：https://github.com/hellof2e/quark-design-docs/commit/d907af1f896786e21c1d1af5ff868adaff0755bb
