### ISSUE TITLE
[Feature request]: 添加 SwipeCell 左滑/右滑功能

### ISSUE THREAD

**Issue by yoyo837** [hellof2e/quark-design#252]
### A description of the problem, steps to reproduce, or with code samples, can be hosted on a GitHub repository with a link to the repository. (问题说明，重现步骤，或附上代码示例，可存放 GitHub 仓库并提供仓库链接。)

左滑后可自定义添加不多于3个的功能, 如:

<img width="360" alt="image" src="https://user-images.githubusercontent.com/6134547/231624568-3b10d90f-f1c5-40a5-8bb6-badf0071d042.png"><img width="351" alt="image" src="https://user-images.githubusercontent.com/6134547/233836186-31b25fe1-e9b6-4d34-b5dd-d87781fc0580.png">

**Comment by sanqi-med** [comment]
已支持： https://github.com/hellof2e/quark-design/pull/288

**Comment by yoyo837** [comment]
> 已支持： #288

666 👍
