### ISSUE TITLE
怎样全局加载组件

### ISSUE THREAD

**Issue by aboutZZ** [hellof2e/quark-design#260]
### A description of the problem, steps to reproduce, or with code samples, can be hosted on a GitHub repository with a link to the repository. (问题说明，重现步骤，或附上代码示例，可存放 GitHub 仓库并提供仓库链接。)

文档中只介绍了按需加载组件，如何将组件一次性全部引入？

**Comment by xsf0105** [comment]
![image](https://github.com/hellof2e/quark-design/assets/14307551/116fbcf6-80c1-4789-a880-92dff6932f47)

https://quark-design.hellobike.com/#/zh-CN/guide/quickstart

**Comment by xsf0105** [comment]
```
import "quarkd/lib"
```
