### ISSUE TITLE
请问如何做移动端适配？

### ISSUE THREAD

**Issue by topazur** [hellof2e/quark-design#266]
### A description of the problem, steps to reproduce, or with code samples, can be hosted on a GitHub repository with a link to the repository. (问题说明，重现步骤，或附上代码示例，可存放 GitHub 仓库并提供仓库链接。)

比如 [vant docs](https://vant-contrib.gitee.io/vant/v2/#/zh-CN/advanced-usage#liu-lan-qi-gua-pei)

**Comment by topazur** [comment]
使用 cssvar 覆盖吗？

**Comment by topaz-h** [comment]
默认vw，没问题了！

**Comment by topazur** [comment]
默认vw，没问题了！
