### ISSUE TITLE
能否提供PickerView组件

### ISSUE THREAD

**Issue by kkfive** [hellof2e/quark-design#268]
### A description of the problem, steps to reproduce, or with code samples, can be hosted on a GitHub repository with a link to the repository. (问题说明，重现步骤，或附上代码示例，可存放 GitHub 仓库并提供仓库链接。)

如题，我想实现支付宝账单这样的选择器，缺少一个可以滚动的容器即pickerView

![image](https://github.com/hellof2e/quark-design/assets/82026204/1a05821f-952d-401c-b2e1-88ffd4a50473)

**Comment by sanqi-med** [comment]
我们针对Picker有三个组件
Picker：https://vue-quarkdesign.hellobike.com/#/zh-CN/component/picker
Cascadepicker: https://vue-quarkdesign.hellobike.com/#/zh-CN/component/cascadepicker
Datetimepicker： https://vue-quarkdesign.hellobike.com/#/zh-CN/component/datetimepicker

应该可以满足你们场景

**Comment by kkfive** [comment]
emmmm  我的表达可能不太清楚

我目前想要的其实是单独的一个 picker-column 组件，因为我要实现图上的那个功能。组件库提供的组件都有一个popup的弹窗，并且我无法在该弹窗中添加或修改内容。因此我准备自己实现如图的选择器。（如果组件库可以提供那更好了😄）

![image](https://github.com/hellof2e/quark-design/assets/82026204/27463cd7-ab3d-4fd0-918a-d6d63ea75bdf)

**Comment by sanqi-med** [comment]
> emmmm 我的表达可能不太清楚
> 
> 我目前想要的其实是单独的一个 picker-column 组件，因为我要实现图上的那个功能。组件库提供的组件都有一个popup的弹窗，并且我无法在该弹窗中添加或修改内容。因此我准备自己实现如图的选择器。（如果组件库可以提供那更好了😄）
> 
> ![image](https://user-images.githubusercontent.com/82026204/246352884-27463cd7-ab3d-4fd0-918a-d6d63ea75bdf.png)

类似这个吗？https://mobile.ant.design/zh/components/picker-view
这个后期会计划实现，也欢迎提 PR 实现 PickerView

**Comment by sanqi-med** [comment]
已支持，https://github.com/hellof2e/quark-design/pull/300
