### ISSUE TITLE
Checkbox文案过长时，选择框会变形

### ISSUE THREAD

**Issue by frontYang** [hellof2e/quark-design#270]
### A description of the problem, steps to reproduce, or with code samples, can be hosted on a GitHub repository with a link to the repository. (问题说明，重现步骤，或附上代码示例，可存放 GitHub 仓库并提供仓库链接。)

![image](https://github.com/hellof2e/quark-design/assets/16046879/986853f3-d548-4ece-92d3-f7f64a22a937)

**Comment by sanqi-med** [comment]
v1.0.67版本已修复：https://github.com/hellof2e/quark-design/commit/33d66b35fd90535294e9d76b68c0b1cb63f04955
