### ISSUE TITLE
建议组件文档这里对不同的技术栈提供不同的用法

### ISSUE THREAD

**Issue by Zebra-web** [hellof2e/quark-design#29]
目前只提供了vue和react的用法，其他的我觉着也得来一份（公司使用Angular，移动端用ionic），有的话会直观一点，光靠看vue用法转换多少都得花点时间
虽然你们才刚开源不久，但不依赖技术栈这点值得关注，毕竟国内ng能用的资源本就不多

**Comment by xxxsf** [comment]
收到，后面会抽空补充其他技术栈文档，感谢支持
