### ISSUE TITLE
[Feature Request]Toast 消失时添加过度效果

### ISSUE THREAD

**Issue by yoyo837** [hellof2e/quark-design#297]
目前 Toast 是直接消失的, 添加过度效果, 或者可选的过度效果.

**Comment by yuhaiyang1** [comment]
fixed 
更新内容参见 [CHANGELOG](https://github.com/hellof2e/quark-design/blob/main/packages/quarkd/CHANGELOG.md)。

Please refer to [CHANGELOG](https://github.com/hellof2e/quark-design/blob/main/packages/quarkd/CHANGELOG.md) for details.
