### ISSUE TITLE
官网文档-ImagePreview 图片预览

### ISSUE THREAD

**Issue by wang-cola** [hellof2e/quark-design#3]
![image](https://user-images.githubusercontent.com/21015798/198539640-f8f40605-fae7-4024-8740-b952af0ef0cd.png)
这里点击有问题

**Comment by yuhaiyang1** [comment]
> 
fix 在1.0.8

**Comment by wang-cola** [comment]
> > 
> 
> fix 在1.0.8

1.0.8是什么意思 没看到有什么tag或者版本号

**Comment by yuhaiyang1** [comment]
>


> npm 版本，官网左上角那个就是版本号，现在 demo 预览好了
