### ISSUE TITLE
[Bug Report] Toast Loading 消失动画问题

### ISSUE THREAD

**Issue by zhuokuang** [hellof2e/quark-design#306]
### 问题描述
官网 Toast Demo 中，【函数式调用】的最后一个例子，点击出现 Toast Loading，三秒后 Loading 直接消失，文案会突然闪一下居中，之后随着 Toast 逐渐消失。

### 复现视频
https://github.com/hellof2e/quark-design/assets/58252152/8171cc13-df04-4a54-9824-de543d5a7b3f

### 原因
quark-toast 中的 show 为 true 时，quark-loading `display: block`；当 show 变为 false 的一瞬间，quark-loading `display: none`，loading 瞬间消失，但是 toast 是过渡消失的。

**Comment by yuhaiyang1** [comment]
已修复v1.4.1 https://github.com/hellof2e/quark-design/commit/b8e7c818ccdec287cbf246f869cbf8926f82a64b
