### ISSUE TITLE
The Area Covered by Toast Component cannot be Clicked（Toast组件覆盖区域无法被点击）

### ISSUE THREAD

**Issue by w1475963** [hellof2e/quark-design#324]
When I use ` Toast.text("Anything.") ` , the page will display the Toast component. When this Toast component disappears, the webpage area covered by the original Toast component cannot be clicked.
I tried this process on the official website example, but the Toast coverage still cannot be clicked.

当我使用` Toast.text("Anything.") ` 后，页面中会显示Toast组件，当这个Toast组件消失后，原来Toast组件所覆盖的网页区域无法被点击。
我在官网示例上尝试这一过程，Toast 覆盖区域依然无法被点击。

**Comment by yuhaiyang1** [comment]
fix  by https://github.com/hellof2e/quark-design/commit/fd1e05e3850205b6f3713a98878a6b632e353e77
