### ISSUE TITLE
在微信打开 List 的组件，展示有问题。

### ISSUE THREAD

**Issue by Maidang1** [hellof2e/quark-design#35]
![image](https://user-images.githubusercontent.com/50993231/199152954-4ca162ac-5d9f-4d98-b3c7-c554e2a485aa.png)

机型: 11 pro max
版本: IOS 15.3.1
微信版本: 8.0.23

**Comment by sanqi-med** [comment]
fixed

**Comment by Maidang1** [comment]
> fixed

I want to know why cause the problem, can you paste the pr here

**Comment by zhuokuang** [comment]
> 

https://github.com/hellof2e/quark-design/pull/97

**Comment by zhuokuang** [comment]
> > fixed
> 
> I want to know why cause the problem, can you paste the pr here. thanks

Two reasons:
1. scroll event don't bubble, but can be captured.
2. when list component mounted, check function will run twice, the latter will replace the former because of delay function, but the latter will return directly, so load event will not be emit.
