### ISSUE TITLE
[按钮]  设置事件会重复执行

### ISSUE THREAD

**Issue by lx-summer** [hellof2e/quark-design#56]
### Quark Design 版本

1.0.12

### 重现步骤

import React, { useState } from 'react';
import { Button } from '@quarkd/quark-react';
// import { Button } from 'antd';

const Index = () => {
  const [count, setCount] = useState(0);
  console.log(count);
  return (
    <div>
      <Button
        onClick={(e) => {
          setCount((count) => count + 1);
        }}
      >
        我是一个按钮 {count}
      </Button>
    </div>
  );
};

export default Index;

### 期望结果

1

### 实际结果

2

### 框架版本

react

**Comment by Maidang1** [comment]
<img width="1575" alt="image" src="https://user-images.githubusercontent.com/50993231/199289519-013fb7bb-4bc0-4f57-a152-bfe731e3b237.png">

研究了一下 不明白为啥 update 两次，坐等官方解释一手

**Comment by vaakian** [comment]
这是 React 18 之后在开发模式时故意渲染的两次，防止你忘记清除副作用（side-effect，比如addEventListener就是一个副作用）。

https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects
https://zh-hans.reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects
https://www.google.com/search?q=react+18+double+render

**Comment by Maidang1** [comment]
但是好像影响到了外面，导致 onclick 事件执行了两次，点击数字就从 0 变成了 2

**Comment by vaakian** [comment]
我试了一下，被执行两次就不是React 18 的2次渲染的原因了（只有生命周期渲染的2次是）。
所以 **按钮事件被调用2次** 确实是一个Bug。

**Comment by vaakian** [comment]
尝试将下面的行删除掉就正常了：

https://github.com/hellof2e/quark-design/blob/a4c4b7f0b538b2d723a98c0809b156cbff154899/packages/quark-reactify/src/index.ts#L22

**所以应该是：**
在props透传给原生web-component的时候就已经注册了一次事件，然后自己又手动注册了一次。

https://github.com/hellof2e/quark-design/blob/a4c4b7f0b538b2d723a98c0809b156cbff154899/packages/quark-reactify/src/index.ts#L63

**Comment by Maidang1** [comment]
> 尝试将下面的行删除掉就正常了：
> 
> https://github.com/hellof2e/quark-design/blob/a4c4b7f0b538b2d723a98c0809b156cbff154899/packages/quark-reactify/src/index.ts#L22
> 
> **所以应该是：** 在props透传给原生web-component的时候就已经注册了一次事件，然后自己又手动注册了一次。
> 
> https://github.com/hellof2e/quark-design/blob/a4c4b7f0b538b2d723a98c0809b156cbff154899/packages/quark-reactify/src/index.ts#L63
一会我再研究一下 昨天大致看一眼

**Comment by vaakian** [comment]
> 

已经确定Bug逻辑了：
- 原生的事件（`onClick`，`onMouseOver`，`onMouseUp`）会被 React 自动注册，
- 框架自定义的事件则不会被 React 注册（比如Dialog组件的`onConfirm`，`onCancel`）

所以这里需要做一个列表判断，是否是属于原生事件，或者干脆函数把类型的 prop 不透传到 createElement（但太一刀切了）。

**Comment by sanqi-med** [comment]
@vaakian 你的理解是对的，这边暂时针对click事件已经做了过滤处理了，组件暂时还未使用到其它原生事件，后期如果有其它事件会做个列表判断，或者你那边也可以提PR哈。

**Comment by sanqi-med** [comment]
已修复

**Comment by Maidang1** [comment]
> @vaakian 你的理解是对的，这边暂时针对click事件已经做了过滤处理了，组件暂时还未使用到其它原生事件，后期如果有其它事件会做个列表判断，或者你那边也可以提PR哈。

这样只针对 click 判断也有问题吧 注册了鼠标事件也是一样的吧

**Comment by CVopen** [comment]
> @vaakian你的理解是判断对其他其他此类事件的点击已经进行了过滤处理，某些事件，有时可能会使用到某个事件，如果有事件会做个列表，或者你也提提 PR 。

<img width="1308" alt="image" src="https://user-images.githubusercontent.com/63775524/199447170-0fbae9c6-e902-4f40-8894-48c4598ac141.png">
<img width="711" alt="image" src="https://user-images.githubusercontent.com/63775524/199447579-aae7f6be-d459-4bd8-94cd-3f17be4fa9d9.png">

鼠标和键盘事件同样会执行两次

**Comment by sanqi-med** [comment]
quark 组件目前使用的原生事件三个： click、 blur、 focus、这三个事件已经做了filter。其它原生事件组件内部并未使用，使用quark 组件哪种场景需要再传额外的原生事件呢
