### ISSUE TITLE
rate评分组件 点击评分有bug

### ISSUE THREAD

**Issue by Async-Lee** [hellof2e/quark-design#6]
在文档示例中  点击选中4星的评分的时候，变成5星啦

**Comment by yuhaiyang1** [comment]
> <img alt="image" width="415" src="https://user-images.githubusercontent.com/26810702/198919367-1e80a6c4-528f-4a4d-9fe4-ba6ff98ac80c.png">
> 
> <img alt="image" width="231" src="https://user-images.githubusercontent.com/26810702/198919386-2fd30cf2-8e66-4f9c-bce1-c4ff4d0a5f03.png">

官网修复了，可能需要清一下静态资源缓存
