### ISSUE TITLE
[quark] 希望能提供无样式且支持独立引入的组件

### ISSUE THREAD

**Issue by helsonxiao** [hellof2e/quark-design#71]
### 这个功能解决了什么问题

quark 以 web-components 作为基础来实现，跨框架的思路很棒，但在现有 / 复杂项目中引入整个 UI 库比较困难，而且设计风格不一致，即使覆盖样式后也可能会在升级后出现样式不兼容的情况。希望能够像 [`radix-ui`](https://github.com/radix-ui/primitives) 一样，给开发者最大的样式自定义自由，并且支持单独安装（独立组件 package），这样会比较便于使用。

### 你建议的方案是什么

- 渐进式地将组件拆成 package，开发者只需要安装 core package, component package, framework wrapper package 即可使用。
  - 举个例子，业务上曾有 marquee 的需求，我实现了一个 [web-components 的版本](https://github.com/helsonxiao/pony-marquee)来试用是比较容易接受的，但一下子引入整个 UI 库不是那么容易的事情。
- 默认样式作为可选项，方便开发者自定义样式。

**Comment by xxxsf** [comment]
很棒的建议

**Comment by helsonxiao** [comment]
> 很棒的建议

😊 期待后续的迭代，我可以参与贡献 marquee 组件

**Comment by yuhaiyang1** [comment]
> > 很棒的建议
> 
> 😊 期待后续的迭代，我可以参与贡献 marquee 组件

我已经实现了，可以帮忙优化下

**Comment by helsonxiao** [comment]
> > > 很棒的建议
> > 
> > 
> > 😊 期待后续的迭代，我可以参与贡献 marquee 组件
> 
> 我已经实现了，可以帮忙优化下

😁 能先拆组件包嘛，能单独使用就有优化的动力了。
