### ISSUE TITLE
uploader 手机端打开上传图片时不弹出相机和相册选项直接进入了相册

### ISSUE THREAD

**Issue by glIrving** [hellof2e/quark-design#73]
### Quark Design 版本

new

### 期望结果

希望能有选择性的在底部弹出的相册/相机二选一进行上传

**Comment by yuhaiyang1** [comment]
> ### Quark Design 版本
> new
> 
> ### 重现链接
> _No response_
> 
> ### 重现步骤
> _No response_
> 
> ### 期望结果
> 希望能有选择性的在底部弹出的相册/相机二选一进行上传
> 
> ### 实际结果
> _No response_
> 
> ### 框架版本
> _No response_
> 
> ### 浏览器版本
> _No response_
> 
> ### 系统版本
> _No response_
> 
> ### Node版本
> _No response_
> 
> ### 补充说明
> _No response_

提供下什么浏览以及具体步骤，大部分浏览器都是可以选择的，比如微信直接打开就可以
