### ISSUE TITLE
[image] image、upload等个别组件存在引用缺失

### ISSUE THREAD

**Issue by ymind** [hellof2e/quark-design#75]
### Quark Design 版本

1.0.12

### 重现步骤

导入1.0.12后即可复现该错误，见图：
![fedf7e0b6e75b865c4d40ea8cafe017](https://user-images.githubusercontent.com/315716/199432673-f42b454a-73b3-410b-bb28-da75400fb5af.jpg)

### 框架版本

任意

### Node版本

16

**Comment by sanqi-med** [comment]
已修复
