### ISSUE TITLE
有考虑对Lit 框架进行支持吗

### ISSUE THREAD

**Issue by parselife** [hellof2e/quark-design#83]
Lit 本身也是个开发wc的库，可否利用 quark 作为 ui 框架在 Lit 中使用，是否有比较好的例子可以参考？

**Comment by sanqi-med** [comment]
Lit 是一个开发 wc 组件的框架，quark 是作为组件库的，在 Lit 中使用 quark 是什么场景？
如果是需要自己写组件可以使用@quarkd/core或者Lit或者给quark提PR贡献自己的组件哈
