### ISSUE TITLE
组件文档滚动条问题

### ISSUE THREAD

**Issue by IDP554** [hellof2e/quark-design#9]
具体情况如图：
![image](https://user-images.githubusercontent.com/29688960/198946157-f4dea89d-ab02-469b-9d01-46f795db9cd3.png)
这样会导致在看完上一个组件的api时，下一个组件的内容并不是从头开始，而是处在一个奇怪的位置。

**Comment by xxxsf** [comment]
收到

**Comment by xxxsf** [comment]
好的，感谢反馈，后面会优化

**Comment by sanqi-med** [comment]
已修复
